[package]
name = "color_columns"
version = "0.1.0"
authors = ["Rade Drmić <rdrmic@gmail.com>"]
edition = "2021"

[dependencies]
ggez = "0.7.0"
winit = "0.25.0"
rand = "0.8.4"
glam = "0.20.1"
dirs = "4.0.0"
